[workspace]
resolver = "2"
members = ["crates/sabidvi-format", "crates/sabidvi-special", "crates/sabidvi-page", "crates/sabidvi-fonts", "crates/sabidvi-cli", "crates/sabidvi-wasm"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/syzygy-inc/SabiDVI"

[workspace.dependencies]
sabiface-metrics = { git = "https://github.com/syzygy-inc/SabiFace.git", rev = "47d16ca" }
sabiface-glyph = { git = "https://github.com/syzygy-inc/SabiFace.git", rev = "47d16ca" }
sabiface-map = { git = "https://github.com/syzygy-inc/SabiFace.git", rev = "47d16ca" }
sabirender-display = { git = "https://github.com/syzygy-inc/SabiRender.git", rev = "d0ac8b0" }
sabirender-content = { git = "https://github.com/syzygy-inc/SabiRender.git", rev = "d0ac8b0" }
sabirender-raster = { git = "https://github.com/syzygy-inc/SabiRender.git", rev = "d0ac8b0" }
sabirender-svg = { git = "https://github.com/syzygy-inc/SabiRender.git", rev = "d0ac8b0" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
